<?php use Platform\Services\ApplicationView;
ui_header('Đơn ứng tuyển của tôi','Theo dõi trạng thái pipeline và xem chi tiết AI score cho từng vị trí.'); ?>
<div data-applications-list>
<?php if($data):$stats=['AI đang chấm'=>0,'Ứng tuyển thành công'=>0,'HR Đang xem'=>0,'Phỏng vấn'=>0,'Đề nghị'=>0];foreach($data as $a){if(ApplicationView::screening($a))$stats['AI đang chấm']++;$label=ApplicationView::label($a);if($label!=='AI đang chấm'&&isset($stats[$label]))$stats[$label]++;} ?>
<div class="stat-cards section"><?php foreach($stats as $label=>$count): ?><div class="panel"><span class="muted"><?= e($label) ?></span><strong><?= $count ?></strong></div><?php endforeach; ?></div>
<?php else: ?><section class="panel empty"><h2>Chưa có đơn ứng tuyển</h2><p class="muted">Khám phá việc làm và nộp hồ sơ để nhận điểm AI.</p><a class="button" href="/jobs">Xem việc làm</a></section><?php endif; ?>
<?php foreach($data as $a):$withdrawn=$a['status']==='WITHDRAWN'; ?><article class="panel application-card section" data-application-card="<?= e($a['id']) ?>" data-status="<?= e($a['status']) ?>" data-score="<?= e($a['aiResult']['overallScore']??'') ?>"><div class="company-initial"><?= e(mb_substr($a['job']['company']['name'],0,2)) ?></div><div class="application-body"><h2><a href="/applications/<?= e($a['id']) ?>"><?= e($a['job']['title']) ?></a></h2><p class="muted"><?= e($a['job']['company']['name']) ?> · <?= e($a['job']['location']??'Remote') ?></p><small class="muted">Nộp <?= e(date('d/m/Y',strtotime($a['appliedAt']))) ?></small><?php if(!$withdrawn&&$a['offer']&&$a['offer']['status']==='PENDING'): ?><p class="badge">Bạn có thư mời nhận việc</p><?php endif; ?></div><div><span class="status-badge status-<?= e($a['status']) ?>"><?= e(ApplicationView::label($a)) ?></span>
<?php if(!$withdrawn): ?><p class="positive"><?= ApplicationView::screening($a)?'AI đang phân tích CV':(ApplicationView::hasScore($a)?'Điểm AI: '.e($a['aiResult']['overallScore']).'/100':'Chưa có điểm AI') ?></p><?php endif; ?>
<div class="row section"><a class="button ghost" href="/applications/<?= e($a['id']) ?>">Chi tiết</a><?php if(!$withdrawn&&ApplicationView::hasScore($a)): ?><a class="button" href="/ai-score/<?= e($a['id']) ?>">Xem AI Score</a><?php endif; ?><?php if($withdrawn): ?><button data-action="/applications/<?= e($a['id']) ?>/reapply" data-reload>Ứng tuyển lại</button><?php elseif(!in_array($a['status'],['HIRED','REJECTED'],true)): ?><button class="ghost" data-action="/applications/<?= e($a['id']) ?>" data-method="DELETE" data-confirm="Bạn chắc chắn muốn rút đơn ứng tuyển này?" data-reload>Rút đơn</button><?php endif; ?></div></div></article><?php endforeach; ?>
</div>
