<?php $signup=$path==='/auth/sign-up';$forgot=$path==='/auth/forgot-password'; ?>
<div class="auth-page <?= $signup||$forgot?'auth-redesign':'' ?>">
<?php if($signup||$forgot): ?><div class="auth-redesign-heading"><span class="auth-symbol"><?= $forgot?ui_icon('lock',28):'TF' ?></span><h1><?= $forgot?'Quên mật khẩu?':'Tạo tài khoản' ?></h1><p class="muted"><?= $forgot?'Nhập email hoặc số điện thoại để lấy lại mật khẩu':'Tham gia TalentFlow và khám phá cơ hội nghề nghiệp AI-powered' ?></p></div><?php else: ui_header('Đăng nhập','Dùng email/password hoặc chọn tài khoản demo để trải nghiệm đầy đủ tính năng.'); endif; ?>
<?php if($path==='/auth/oauth-callback'): ?><section class="panel"><p>Đang hoàn tất đăng nhập...</p><a class="button" href="/profile">Tiếp tục</a></section><?php else: ?>
<?php if($signup): ?><div class="role-selector" role="group" aria-label="Loại tài khoản"><button type="button" class="role-option active" data-role="CANDIDATE" aria-pressed="true"><?= ui_icon('user',24) ?><strong>Ứng viên</strong><small>Tìm việc & phát triển sự nghiệp</small></button><button type="button" class="role-option" data-role="RECRUITER" aria-pressed="false"><?= ui_icon('briefcase',24) ?><strong>Nhà tuyển dụng</strong><small>Đăng tin & tuyển nhân tài</small></button></div><?php endif; ?>
<section class="panel" id="auth-form-panel"><form data-api="<?= $signup?'/auth/register':($forgot?'/auth/forgot-password':'/auth/login') ?>" <?= $forgot?'data-success="recovery-success"':($signup?'data-register':'data-redirect="/"') ?>>
<?php if($signup): ?><input type="hidden" name="role" value="CANDIDATE"><label>Họ và tên<input name="fullName" placeholder="Nguyễn Văn A" required autocomplete="name"></label><label>Tên tài khoản<input name="username" placeholder="nguyenvana" required pattern="[a-zA-Z0-9_]{3,30}" maxlength="30" autocomplete="username"><small class="muted">3–30 ký tự: chữ, số và dấu gạch dưới.</small></label><label>Số điện thoại<input name="phone" type="tel" required pattern="[+0-9 -]{8,20}" placeholder="0901 234 567" autocomplete="tel"></label><?php endif; ?>
<label>Email<input name="email" type="email" placeholder="you@example.com" autocomplete="email" <?= $forgot?'':'required' ?>></label>
<?php if($forgot): ?><p class="auth-divider">HOẶC</p><label>Số điện thoại<input name="phone" type="tel" placeholder="0901 234 567" autocomplete="tel"></label><?php else: ?><label><?= $signup?'Mật khẩu':'Password' ?><span class="password-field"><input name="password" type="password" placeholder="••••••••" minlength="8" autocomplete="<?= $signup?'new-password':'current-password' ?>" required><?php if($signup): ?><button type="button" class="icon-button" data-password-toggle aria-label="Hiển thị mật khẩu"><?= ui_icon('eye',16) ?></button><?php endif; ?></span></label><?php if($signup): ?><label>Xác nhận mật khẩu<input name="confirmPassword" type="password" placeholder="••••••••" autocomplete="new-password" required></label><?php endif; endif; ?>
<p class="form-error" role="alert" hidden></p><?php if(!$signup&&!$forgot): ?><div class="field-end"><a href="/auth/forgot-password">Quên mật khẩu?</a></div><?php endif; ?><button type="submit"><?= $signup?'Tạo tài khoản':($forgot?'Gửi yêu cầu lấy lại mật khẩu':'Đăng nhập') ?></button></form>
<?php if(!$signup&&!$forgot&&(env('GOOGLE_CLIENT_ID')||env('LINKEDIN_CLIENT_ID'))): ?><div class="auth-social"><?php foreach(['google'=>'Google','linkedin'=>'LinkedIn'] as $provider=>$label):if(env(strtoupper($provider).'_CLIENT_ID')): ?><button class="ghost" data-oauth="<?= e($provider) ?>"><?= e($label) ?></button><?php endif;endforeach; ?></div><?php endif; ?></section>
<?php if($forgot): ?><section id="recovery-success" class="panel recovery-success" hidden><?= ui_icon('check',48) ?><h2>Yêu cầu đã gửi!</h2><p>Yêu cầu của bạn đã được chuyển đến quản trị viên. Quản trị viên sẽ kiểm tra thông tin và hỗ trợ khôi phục tài khoản.</p><a class="button ghost" href="/auth/sign-in">← Quay lại đăng nhập</a></section><?php endif; ?>
<?php if(!$signup&&!$forgot&&env('DEMO_LOGIN')==='true'): ?><section class="panel"><h2>Tài khoản demo nhanh</h2><p class="muted">Click để đăng nhập không cần nhập mật khẩu.</p><?php foreach(['candidate'=>['Nguyễn Minh Anh','Ứng viên'],'recruiter'=>['TalentFlow Recruiter','Nhà tuyển dụng'],'admin'=>['TalentFlow Admin','Quản trị viên']] as $account=>[$name,$role]): ?><button class="demo-option" data-action="/auth/demo-login?email=<?= e(rawurlencode($account.'@demo.local')) ?>" data-method="GET" data-redirect="/"><strong><?= e($name) ?></strong><small><?= e($role) ?></small></button><?php endforeach; ?></section><?php endif; ?>
<p class="auth-bottom"><?= $forgot?'Nhớ mật khẩu rồi?':($signup?'Đã có tài khoản?':'Chưa có tài khoản?') ?> <a href="<?= $signup||$forgot?'/auth/sign-in':'/auth/sign-up' ?>"><?= $signup||$forgot?'Đăng nhập ngay':'Đăng ký ngay' ?></a></p><?php endif; ?></div>