<?php $internal=$path==='/jobs';$savedIds=$user?$app->api($internal?'users/me/saved-jobs/ids':'external-jobs/saved/ids'):[];$userSkillNames=[];if($user)foreach($app->api('users/me/skills') as $skill)$userSkillNames[]=strtolower($skill['skill']['name']);
$filters=$request->query;$selected=function($name,$value)use($filters){return ($filters[$name]??'')===$value?'selected':'';}; ?>
<?php ui_header($internal?'Việc làm đang tuyển':'Việc làm tổng hợp',$internal?'Lọc theo kỹ năng, địa điểm, lương và cấp bậc. Tìm kiếm nâng cao như TopCV.':'Khám phá cơ hội từ ITviec, CareerViet, TopCV và VietnamWorks. Chấm điểm CV trước khi ứng tuyển.'); ?>
<form method="get" id="job-filters" class="panel jobs-search"><label>Tìm kiếm<div class="field-icon"><?= ui_icon('search',18) ?><input name="keyword" placeholder="Backend, React, Data Engineer..." value="<?= e($filters['keyword']??'') ?>"></div></label><label class="location-field">Địa điểm<div class="field-icon"><?= ui_icon('pin',18) ?><input name="location" placeholder="Hà Nội, HCM..." value="<?= e($filters['location']??'') ?>"></div></label><button>Tìm kiếm</button></form>
<button class="ghost mobile-filter-toggle section" style="display:none" data-mobile-filters aria-expanded="false"><?= ui_icon('filter') ?>Bộ lọc</button>
<div class="jobs-layout"><aside class="filter-sidebar"><section class="panel"><div class="filter-title"><strong><?= ui_icon('filter') ?>Bộ lọc</strong><a href="<?= e($path) ?>">Đặt lại</a></div>
<?php if(!$internal): ?><label>Nguồn tuyển dụng<select name="source" form="job-filters" data-filter-change><option value="">Tất cả nguồn</option><?php foreach(['topcv'=>'TopCV','itviec'=>'ITviec','careerviet'=>'CareerViet','vietnamworks'=>'VietnamWorks'] as $value=>$label): ?><option value="<?= e($value) ?>" <?= $selected('source',$value) ?>><?= e($label) ?></option><?php endforeach; ?></select></label><?php endif; ?>
<label>Cấp bậc<select name="level" form="job-filters" data-filter-change><option value="">Tất cả</option><?php foreach(['INTERN','JUNIOR','MID','SENIOR','LEAD','MANAGER'] as $level): ?><option <?= $selected('level',$level) ?>><?= e($level) ?></option><?php endforeach; ?></select></label>
<?php if($internal): ?><label>Hình thức<select name="jobType" form="job-filters" data-filter-change><option value="">Tất cả</option><?php foreach(['FULL_TIME','PART_TIME','CONTRACT','INTERNSHIP'] as $type): ?><option <?= $selected('jobType',$type) ?>><?= e($type) ?></option><?php endforeach; ?></select></label><label>Danh mục<input name="category" form="job-filters" value="<?= e($filters['category']??'') ?>"></label><label>Lương tối thiểu<input name="salaryMin" form="job-filters" type="number" min="0" value="<?= e($filters['salaryMin']??'') ?>"></label><label>Lương tối đa<input name="salaryMax" form="job-filters" type="number" min="0" value="<?= e($filters['salaryMax']??'') ?>"></label><label><input name="isRemote" form="job-filters" type="checkbox" value="true" <?= ($filters['isRemote']??'')==='true'?'checked':'' ?> data-filter-change>Chỉ việc làm Remote</label>
<?php elseif($user): ?><label><input name="savedOnly" form="job-filters" type="checkbox" value="true" <?= ($filters['savedOnly']??$filters['saved']??'')==='true'?'checked':'' ?> data-filter-change>Chỉ việc làm đã lưu</label><?php endif; ?><button form="job-filters" class="ghost" style="width:100%">Áp dụng bộ lọc</button></section></aside>
<section><div class="jobs-results-heading"><strong><?= (int)$data['total'] ?> vị trí phù hợp</strong><?php if($internal): ?><label style="margin:0">Sắp xếp: <select name="sort" form="job-filters" data-filter-change><?php foreach(['newest'=>'Mới nhất','salary'=>'Lương cao nhất','relevance'=>'Phổ biến'] as $value=>$label): ?><option value="<?= e($value) ?>" <?= $selected('sort',$value) ?>><?= e($label) ?></option><?php endforeach; ?></select></label><?php endif; ?></div>
<?php if(!$data['items']): ?><article class="panel empty-state"><?= ui_icon('search',36) ?><h2>Không tìm thấy việc làm</h2><p>Thử đổi bộ lọc hoặc quay lại sau.</p><a href="<?= e($path) ?>" class="button secondary">Đặt lại bộ lọc</a></article><?php else: ?><div class="grid cards"><?php foreach($data['items'] as $job): require APP_ROOT.'/views/partials/job-card.php';endforeach; ?></div><?php endif; ?>
<nav class="pagination" aria-label="Phân trang"><?php if($data['page']>1): ?><a class="button secondary" href="?<?= e(http_build_query(array_merge($filters,['page'=>$data['page']-1]))) ?>">Trước</a><?php endif; ?><span>Trang <?= (int)$data['page'] ?>/<?= max(1,(int)ceil($data['total']/$data['limit'])) ?></span><?php if($data['page']*$data['limit']<$data['total']): ?><a class="button secondary" href="?<?= e(http_build_query(array_merge($filters,['page'=>$data['page']+1]))) ?>">Sau</a><?php endif; ?></nav>
</section></div>
<?php if(!$internal): ?><dialog id="job-summary" class="ui-dialog"><div class="dialog-heading"><h2>Tóm tắt việc làm</h2><button class="icon-button" data-close-dialog aria-label="Đóng"><?= ui_icon('close') ?></button></div><div class="dialog-body"></div></dialog>
<dialog id="cv-screening" class="ui-dialog screening-drawer"><div class="dialog-heading"><h2 data-screen-title>Chấm điểm CV</h2><button class="icon-button" data-close-dialog aria-label="Đóng"><?= ui_icon('close') ?></button></div><div class="dialog-body"><?php if(!$user): ?><p>Đăng nhập để chọn hoặc tải CV và nhận điểm phù hợp từ AI.</p><a class="button" href="/auth/sign-in">Đăng nhập</a><?php elseif($user['role']!=='CANDIDATE'): ?><p>Chỉ tài khoản ứng viên mới có thể tải và chọn CV.</p><?php else: $cvs=$app->api('users/me/cv'); ?><form data-api="" data-result="screen-result"><label>CV của bạn<select name="cvFileId" required><option value="">Chọn CV</option><?php foreach($cvs as $cv): ?><option value="<?= e($cv['id']) ?>" <?= $cv['isPrimary']?'selected':'' ?>><?= e($cv['fileName']) ?><?= $cv['isPrimary']?' (Mặc định)':'' ?></option><?php endforeach; ?></select></label><label>Hoặc tải lên CV mới<input type="file" data-screen-upload accept=".pdf,.docx"></label><p class="muted" style="font-size:12px">Hỗ trợ PDF, DOCX (tối đa 5MB). AI sẽ đọc nội dung file để chấm điểm.</p><button style="width:100%"><?= ui_icon('sparkles',16) ?>Chấm điểm với AI</button></form><div id="screen-result" class="section"></div><?php endif; ?></div></dialog>
<?php if(!empty($filters['id'])): ?><span hidden data-initial-job="<?= e($filters['id']) ?>"></span><?php endif; endif; ?>
