<?php require_once APP_ROOT.'/views/ui.php';
$isHome=$path==='/';$isRecruiter=$user&&in_array($user['role'],['RECRUITER','ADMIN'],true);
$links=$isRecruiter?[
    ['/recruiter/dashboard','Dashboard','grid'],['/recruiter/jobs/new','Đăng tin','plus'],['/recruiter/analytics','Thống kê','chart'],['/feed','Bảng tin','rss'],['/messages','Tin nhắn','message']
]:($user?[
    ['/feed','Bảng tin','rss'],['/network','Mạng lưới','users'],['/messages','Tin nhắn','message']
]:[['/','Trang chủ','grid'],['/jobs','Việc làm','briefcase'],['/external-jobs','Việc làm tổng hợp','globe'],['/search','Tìm kiếm','search']]);
$jobsLinks=[['/jobs','Việc làm tuyển dụng','Tin tuyển trực tiếp trên TalentFlow','briefcase'],['/external-jobs','Việc làm tổng hợp','TopCV, ITviec, CareerViet, VNW','globe'],['/saved-jobs','Việc làm đã lưu','Danh sách tin đã bookmark','bookmark'],['/applications','Đơn ứng tuyển','Theo dõi tiến độ hồ sơ đã nộp','file']];
$toolLinks=[['/cv-builder','Tạo CV','Thiết kế CV chuyên nghiệp','file'],['/goals','Mục tiêu nghề nghiệp','Lộ trình phát triển của bạn','target'],['/search','Tìm kiếm','Khám phá người, việc làm, công ty','search']];
?>
<!doctype html><html lang="vi"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="<?= e($csrf) ?>"><meta name="description" content="TalentFlow — AI Recruitment Platform"><title><?= e($title) ?></title>
<?php foreach(['original-tokens.css','app.css','restored-ui.css','audit-ui.css'] as $asset): ?><link rel="stylesheet" href="/assets/<?= e($asset) ?>?v=<?= filemtime(APP_ROOT.'/public/assets/'.$asset) ?>"><?php endforeach; ?>
<script>try{var p=JSON.parse(localStorage.getItem('cv_appearance_prefs')||'{}');var t=p.theme||'dark';document.documentElement.dataset.theme=t==='system'?(matchMedia('(prefers-color-scheme:light)').matches?'light':'dark'):t}catch(e){}</script>
<?php foreach(['app.js','restored-ui.js','feed-ui.js','social-ui.js','application-ui.js','chat-ui.js','goals-ui.js'] as $asset): ?><script defer src="/assets/<?= e($asset) ?>?v=<?= filemtime(APP_ROOT.'/public/assets/'.$asset) ?>"></script><?php endforeach; ?></head>
<body data-authenticated="<?= $user?'true':'false' ?>" data-page="<?= e($view) ?>"><a class="skip-link" href="#main-content">Skip to content</a>
<?php if(!$isHome): ?><header class="app-header"><div class="header-inner">
<div class="row"><button class="icon-button mobile-nav-button" data-dialog="mobile-navigation" aria-label="Mở menu"><?= ui_icon('menu',22) ?></button><a class="app-brand" href="<?= $user?($isRecruiter?'/recruiter/dashboard':'/feed'):'/' ?>"><span class="brand-mark">TF</span><span class="brand-name">TalentFlow<small>AI Recruitment</small></span></a></div>
<nav class="desktop-nav" aria-label="Điều hướng chính">
<?php foreach($links as [$href,$label,$icon]): ?><a class="nav-link <?= $path===$href?'active':'' ?>" href="<?= e($href) ?>"><?= ui_icon($icon,16) ?><?= e($label) ?></a><?php endforeach; ?>
<?php if($user&&!$isRecruiter): foreach([['Việc làm','briefcase',$jobsLinks],['Công cụ','sparkles',$toolLinks]] as [$label,$icon,$items]): ?><details class="nav-dropdown"><summary><?= ui_icon($icon,16) ?><?= e($label) ?><?= ui_icon('chevron',14) ?></summary><div class="nav-menu"><?php foreach($items as [$href,$name,$description,$symbol]): ?><a href="<?= e($href) ?>"><?= ui_icon($symbol,20) ?><span><?= e($name) ?><small><?= e($description) ?></small></span></a><?php endforeach; ?></div></details><?php endforeach; endif; ?></nav>
<div class="header-tools"><button class="icon-button" id="theme-toggle" aria-label="Đổi giao diện"><?= ui_icon('moon',18) ?></button>
<?php if($user): ?><a class="icon-button notification-link" href="/notifications" aria-label="Thông báo"><?= ui_icon('bell',20) ?><span id="notification-count" class="unread-dot"></span></a>
<details class="nav-dropdown"><summary class="account-summary"><span class="mini-avatar"><?= e(strtoupper(substr($user['email'],0,1))) ?></span><span><?= e(explode('@',$user['email'])[0]) ?></span><?= ui_icon('chevron',14) ?></summary><div class="nav-menu"><div class="account-info"><p><?= e($user['email']) ?></p><span class="badge"><?= $user['role']==='ADMIN'?'Quản trị viên':($isRecruiter?'Nhà tuyển dụng':'Ứng viên') ?></span></div><a href="/profile"><?= ui_icon('user',16) ?>Hồ sơ của tôi</a><a href="/settings"><?= ui_icon('settings',16) ?>Cài đặt tài khoản</a><?php if($user['role']==='ADMIN'): ?><a href="/admin/moderation"><?= ui_icon('shield',16) ?>Quản trị nội dung</a><?php endif; ?><hr><button data-action="/auth/logout" data-method="POST" data-redirect="/"><?= ui_icon('logout',16) ?>Đăng xuất</button></div></details>
<?php else: ?><a class="button" href="/auth/sign-in">Đăng nhập</a><?php endif; ?></div></div></header>
<dialog class="nav-drawer" id="mobile-navigation"><div class="drawer-header"><a class="app-brand" href="/"><span class="brand-mark">TF</span>TalentFlow</a><button class="icon-button" data-close-dialog aria-label="Đóng menu"><?= ui_icon('close',20) ?></button></div><?php if($user): ?><div class="drawer-account"><?= e($user['email']) ?><p class="muted"><?= $isRecruiter?'Nhà tuyển dụng':'Ứng viên' ?></p></div><?php endif; ?><nav class="drawer-links" aria-label="Menu di động">
<?php foreach($links as [$href,$label,$icon]): ?><a href="<?= e($href) ?>"><?= ui_icon($icon) ?><?= e($label) ?></a><?php endforeach; ?>
<?php if($user&&!$isRecruiter): foreach(array_merge($jobsLinks,$toolLinks) as [$href,$label,$description,$icon]): ?><a href="<?= e($href) ?>"><?= ui_icon($icon) ?><?= e($label) ?></a><?php endforeach; endif; ?>
<a href="/profile"><?= ui_icon('user') ?>Hồ sơ</a><a href="/settings"><?= ui_icon('settings') ?>Cài đặt</a><a href="/notifications"><?= ui_icon('bell') ?>Thông báo</a></nav></dialog>
<?php endif; ?>
<main id="main-content" class="app-content <?= $isHome?'home-content':'' ?>"><div id="feedback" role="status" aria-live="polite"></div><?php require APP_ROOT.'/views/'.$view.'.php'; ?></main>
<?php if(!$isHome): ?><footer class="app-footer"><div class="footer-grid"><div><p class="footer-brand">TalentFlow</p><p>Nền tảng tuyển dụng AI-first kết hợp mạng xã hội nghề nghiệp.</p></div><div><h3>Ứng viên</h3><?php foreach([['/jobs','Tìm việc làm'],['/external-jobs','Việc làm tổng hợp'],['/applications','Đơn ứng tuyển'],['/goals','Mục tiêu nghề nghiệp'],['/feed','Bảng tin']] as [$href,$label]): ?><a href="<?= e($href) ?>"><?= e($label) ?></a><?php endforeach; ?></div><div><h3>Nhà tuyển dụng</h3><a href="/recruiter/dashboard">Dashboard</a><a href="/recruiter/jobs/new">Đăng tin tuyển dụng</a><a href="/recruiter/analytics">Thống kê tuyển dụng</a></div><div><h3>Nền tảng</h3><p>Hệ thống tổng hợp dữ liệu việc làm từ ITviec, CareerViet, TopCV và VietnamWorks.</p></div></div><div class="footer-copy">© 2026 TalentFlow - AI Recruitment Platform</div></footer><?php endif; ?></body></html>
