<?php
declare(strict_types=1);
namespace Platform\Controllers;
use Platform\Http\Request;
use Platform\Http\Error;
use Platform\Services\Visibility;
class Messaging extends Controller {
    protected function routes(): void {
        $this->route('GET','messages/conversations',function(){$u=$this->auth->current();$rows=$this->db->records('conversations','id IN (SELECT conversation_id FROM conversation_participants WHERE user_id=?)',[$u['id']]);foreach($rows as &$c){$c['participants']=$this->db->records('conversation_participants','conversation_id=?',[$c['id']]);foreach($c['participants'] as &$p){$p['user']=$this->safeUser($this->find('users',['id'=>$p['userId']]));$privacy=$this->db->record('privacy_settings',['userId'=>$p['userId']]);$p['online']=($privacy['showConnections']??true)&&(bool)$this->db->one('SELECT user_id FROM user_presence WHERE user_id=? AND last_seen_at>UTC_TIMESTAMP()-INTERVAL 30 SECOND',[$p['userId']]);}$last=$this->db->all('SELECT * FROM messages WHERE conversation_id=? AND deleted_at IS NULL ORDER BY sent_at DESC,id DESC LIMIT 1',[$c['id']]);$c['messages']=array_map(function($m){return $this->db->map('messages',$m);},$last);$c['conversation']=$c;}return $rows;});
        $this->route('POST','messages/conversations',function(Request $r){$u=$this->auth->current();$ids=$r->body['participantIds']??[];if(!is_array($ids)||!$ids||count($ids)>20)throw new Error(400,'Choose 1–20 participants');$ids=array_values(array_unique(array_merge($ids,[$u['id']])));$v=new Visibility($this->db);foreach($ids as $id){$this->find('users',['id'=>$id]);if($id!==$u['id']&&!$v->message($u['id'],$id))throw new Error(403,'Recipient does not allow messages');}if(count($ids)===2){$old=$this->db->one("SELECT c.id FROM conversations c JOIN conversation_participants a ON a.conversation_id=c.id JOIN conversation_participants b ON b.conversation_id=c.id WHERE c.type='DIRECT' AND a.user_id=? AND b.user_id=? LIMIT 1",$ids);if($old)return $this->find('conversations',$old);}return $this->db->transaction(function()use($ids){$c=$this->db->write('conversations',['type'=>count($ids)>2?'GROUP':'DIRECT']);foreach($ids as $id)$this->db->write('conversation_participants',['conversationId'=>$c['id'],'userId'=>$id]);return $c;});});
        $this->route('GET','messages/conversations/{id}',function(Request $r,array $p){$u=$this->auth->current();$this->participant($p['id'],$u['id']);$where=['conversation_id=?','deleted_at IS NULL'];$args=[$p['id']];if(!empty($r->query['q'])){$where[]='content LIKE ?';$args[]='%'.$r->query['q'].'%';}if(!empty($r->query['before'])){$before=$r->query['before'];$older=$this->db->record('messages',['id'=>$before]);if($older){if($older['conversationId']!==$p['id'])throw new Error(400,'Invalid message cursor');$time=(new \DateTimeImmutable($older['sentAt']))->format('Y-m-d H:i:s.v');$where[]='(sent_at<? OR (sent_at=? AND id<?))';array_push($args,$time,$time,$older['id']);}else{try{$time=(new \DateTimeImmutable($before))->format('Y-m-d H:i:s.v');}catch(\Throwable $e){throw new Error(400,'Invalid message cursor');}$where[]='sent_at<?';$args[]=$time;}}return array_reverse(array_map(function($m){return $this->db->map('messages',$m);},$this->db->all('SELECT * FROM messages WHERE '.implode(' AND ',$where).' ORDER BY sent_at DESC,id DESC LIMIT '.$this->limit($r,50),$args)));});
        $this->route('GET','messages/conversations/{id}/poll',function(Request $r,array $p){$u=$this->auth->current();$this->participant($p['id'],$u['id']);$result=$this->poll('messages','conversation_id=? AND deleted_at IS NULL',[$p['id']],'sent_at',$r);$result['typing']=$this->db->all('SELECT user_id userId FROM conversation_typing WHERE conversation_id=? AND user_id<>? AND expires_at>UTC_TIMESTAMP(3)',[$p['id'],$u['id']]);$result['participants']=$this->db->records('conversation_participants','conversation_id=?',[$p['id']]);return $result;});
        $this->route('POST','messages',function(Request $r){$u=$this->auth->current();$id=$r->required('conversationId');$this->participant($id,$u['id']);$content=$r->required('content');if(mb_strlen($content)>5000)throw new Error(400,'Message too long');$v=new Visibility($this->db);foreach($this->db->records('conversation_participants','conversation_id=?',[$id]) as $p)if($p['userId']!==$u['id']&&!$v->message($u['id'],$p['userId']))throw new Error(403,'Recipient does not allow messages');return $this->db->write('messages',['conversationId'=>$id,'senderId'=>$u['id'],'content'=>$content]);});
        $this->route('PATCH','messages/conversations/{id}/read',function(Request $r,array $p){$u=$this->auth->current();$this->participant($p['id'],$u['id']);return $this->db->transaction(function()use($u,$p){$link=$this->db->write('conversation_participants',['lastReadAt'=>\now()],['conversationId'=>$p['id'],'userId'=>$u['id']]);$this->db->run('UPDATE messages SET is_read=1 WHERE conversation_id=? AND sender_id<>?',[$p['id'],$u['id']]);return $link;});});
        $this->route('POST','messages/conversations/{id}/typing',function(Request $r,array $p){$u=$this->auth->current();$this->participant($p['id'],$u['id']);if(empty($r->body['isTyping']))$this->db->run('DELETE FROM conversation_typing WHERE conversation_id=? AND user_id=?',[$p['id'],$u['id']]);else $this->db->run('INSERT INTO conversation_typing(conversation_id,user_id,expires_at) VALUES(?,?,UTC_TIMESTAMP(3)+INTERVAL 5 SECOND) ON DUPLICATE KEY UPDATE expires_at=VALUES(expires_at)',[$p['id'],$u['id']]);return ['ok'=>true];});
        $this->route('POST','presence/heartbeat',function(){$u=$this->auth->current();$this->db->run('INSERT INTO user_presence(user_id,last_seen_at) VALUES(?,UTC_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE last_seen_at=VALUES(last_seen_at)',[$u['id']]);return ['ok'=>true];});
        $this->route('GET','messages/unread-summary',function(){$u=$this->auth->current();return ['unreadCount'=>(int)$this->db->one('SELECT COUNT(*) n FROM messages m JOIN conversation_participants p ON p.conversation_id=m.conversation_id WHERE p.user_id=? AND m.sender_id<>? AND m.deleted_at IS NULL AND (p.last_read_at IS NULL OR m.sent_at>p.last_read_at)',[$u['id'],$u['id']])['n']];});
        $this->route('GET','notifications',function(){return $this->db->records('notifications','user_id=?',[$this->auth->current()['id']],'created_at DESC');});
        $this->route('GET','notifications/poll',function(Request $r){return $this->poll('notifications','user_id=?',[$this->auth->current()['id']],'created_at',$r);});
        $this->route('PATCH','notifications/read-all',function(){$this->db->run('UPDATE notifications SET is_read=1 WHERE user_id=?',[$this->auth->current()['id']]);return ['ok'=>true];});
        $this->route('PATCH','notifications/{id}/read',function(Request $r,array $p){$this->owned('notifications',$p['id']);return $this->db->write('notifications',['isRead'=>true],['id'=>$p['id']]);});
    }
    private function participant(string $conversation,string $user): void {if(!$this->db->record('conversation_participants',['conversationId'=>$conversation,'userId'=>$user]))throw new Error(403,'Conversation access denied');}
    private function poll(string $table,string $where,array $args,string $time,Request $r): array {
        $cursor=$r->query['cursor']??'';if($cursor){$v=json_decode(base64_decode($cursor,true)?:'',true);if(!is_array($v)||count($v)!==2)throw new Error(400,'Invalid polling cursor');$where.=' AND (`'.$time.'`>? OR (`'.$time.'`=? AND id>?))';array_push($args,$v[0],$v[0],$v[1]);}
        $rows=$this->db->all('SELECT * FROM `'.$table.'` WHERE '.$where.' ORDER BY `'.$time.'` ASC,id ASC LIMIT 100',$args);
        if($rows){$last=end($rows);$cursor=base64_encode(json_encode([$last[$time],$last['id']]));}
        return ['items'=>array_map(function($row)use($table){return $this->db->map($table,$row);},$rows),'cursor'=>$cursor];
    }
}
