<?php
declare(strict_types=1);
namespace Platform\Controllers;
use Platform\Http\Request;
use Platform\Http\Error;
class Recruitment extends Controller {
    protected function routes(): void {
        $this->route('GET','companies',function(){return $this->db->records('companies');});
        $this->route('POST','companies',function(Request $r){$u=$this->auth->role(['RECRUITER','ADMIN']);return $this->db->transaction(function()use($r,$u){$data=$this->only($r->body,['name','slug','website','industry','sizeRange','foundedYear','address','description']);$data['name']=$r->required('name');$data['slug']=$r->body['slug']??('company-'.substr(\uuid(),0,8));$c=$this->db->write('companies',$data);$this->db->write('company_members',['companyId'=>$c['id'],'userId'=>$u['id'],'role'=>'OWNER']);return $c;});});
        $this->route('GET','companies/{id}/analytics',function(Request $r,array $p){$this->auth->company($p['id']);return $this->analytics($p['id']);});
        $this->route('GET','companies/{id}/members',function(Request $r,array $p){$this->auth->company($p['id']);return $this->db->records('company_members','company_id=?',[$p['id']]);});
        $this->route('POST','companies/{id}/members',function(Request $r,array $p){$this->auth->company($p['id'],true);$u=$this->find('users',['id'=>$r->required('userId')]);if(!in_array($u['role'],['ADMIN','RECRUITER'],true))throw new Error(400,'Recruiter required');return $this->db->write('company_members',['companyId'=>$p['id'],'userId'=>$u['id'],'role'=>$r->choice('role',['ADMIN','RECRUITER'],'RECRUITER')]);});
        $this->route('GET','companies/{id}',function(Request $r,array $p){$c=$this->find('companies',['id'=>$p['id']]);$c['jobs']=$this->jobs('company_id=? AND status=\'ACTIVE\'',[$c['id']]);$c['followerCount']=(int)$this->db->one('SELECT COUNT(*) n FROM company_followers WHERE company_id=?',[$c['id']])['n'];$company=$c;unset($company['jobs'],$company['followerCount']);$posts=[];$visibility=new \Platform\Services\Visibility($this->db);$viewer=$this->auth->current(false);foreach($this->db->records('posts','company_id=? AND deleted_at IS NULL',[$c['id']],'created_at DESC') as $post)if($visibility->post($post,$viewer)){$post['author']=['profile'=>$this->db->record('user_profiles',['userId'=>$post['authorId']])];$posts[]=$post;}return $c+['company'=>$company,'activeJobs'=>$c['jobs'],'jobsCount'=>count($c['jobs']),'posts'=>$posts];});
        $this->route('GET','companies/{id}/following',function(Request $r,array $p){return ['following'=>(bool)$this->db->record('company_followers',['companyId'=>$p['id'],'userId'=>$this->auth->current()['id']])];});
        $this->route('POST','companies/{id}/follow',function(Request $r,array $p){$this->find('companies',['id'=>$p['id']]);$key=['companyId'=>$p['id'],'userId'=>$this->auth->current()['id']];return $this->db->record('company_followers',$key)??$this->db->write('company_followers',$key);});
        $this->route('DELETE','companies/{id}/follow',function(Request $r,array $p){$this->db->delete('company_followers',['companyId'=>$p['id'],'userId'=>$this->auth->current()['id']]);return ['ok'=>true];});
        $this->route('GET','jobs/search',function(Request $r){return $this->search($r);});
        $this->route('GET','jobs/facets',function(){return ['locations'=>array_column($this->db->all("SELECT DISTINCT location FROM jobs WHERE status='ACTIVE' AND location IS NOT NULL"),'location'),'categories'=>array_column($this->db->all("SELECT DISTINCT category FROM jobs WHERE status='ACTIVE' AND category IS NOT NULL"),'category'),'levels'=>array_column($this->db->all("SELECT DISTINCT level FROM jobs WHERE status='ACTIVE'"),'level')];});
        $this->route('GET','jobs',function(Request $r){return $this->search($r)['items'];});
        $this->route('POST','jobs',function(Request $r){$u=$this->auth->company($r->required('companyId'));$data=$this->only($r->body,array_diff(array_keys($this->db->fields('jobs')),['id','createdBy','viewsCount']));$data['createdBy']=$u['id'];$data['title']=$r->required('title');$data['description']=$r->required('description');$data['jobType']=$r->required('jobType');$data['level']=$r->required('level');$data['status']=$r->choice('status',['DRAFT','ACTIVE','CLOSED'],'DRAFT');$data['requiredSkills']=$r->body['requiredSkills']??[];if($data['status']==='ACTIVE')$data['publishedAt']=\now();return $this->db->write('jobs',$data);});
        $this->route('PATCH','jobs/{id}',function(Request $r,array $p){$j=$this->find('jobs',['id'=>$p['id']]);$this->auth->company($j['companyId']);$data=$this->only($r->body,array_diff(array_keys($this->db->fields('jobs')),['id','companyId','createdBy','viewsCount']));if(isset($data['status']))$r->choice('status',['DRAFT','ACTIVE','CLOSED']);return $this->db->write('jobs',$data,['id'=>$j['id']]);});
        $this->route('GET','jobs/{id}',function(Request $r,array $p){$j=$this->find('jobs',['id'=>$p['id']]);if($j['status']!=='ACTIVE')$this->auth->company($j['companyId']);$this->db->run('UPDATE jobs SET views_count=views_count+1 WHERE id=?',[$j['id']]);return $this->job($j);});
        foreach(['POST','DELETE'] as $method)$this->route($method,'jobs/{id}/save',function(Request $r,array $p)use($method){$this->find('jobs',['id'=>$p['id']]);$k=['userId'=>$this->auth->current()['id'],'jobId'=>$p['id']];if($method==='DELETE'){$this->db->delete('saved_jobs',$k);return ['ok'=>true];}return $this->db->record('saved_jobs',$k)??$this->db->write('saved_jobs',$k);});
        $this->route('GET','users/me/saved-jobs/ids',function(){return array_column($this->db->records('saved_jobs','user_id=?',[$this->auth->current()['id']]),'jobId');});
        $this->route('GET','users/me/saved-jobs',function(){$s=$this->db->records('saved_jobs','user_id=?',[$this->auth->current()['id']]);foreach($s as &$v)$v['job']=$this->job($this->find('jobs',['id'=>$v['jobId']]));return $s;});
        $this->route('POST','applications',function(Request $r){$u=$this->auth->role(['CANDIDATE']);$j=$this->find('jobs',['id'=>$r->required('jobId')]);if($j['status']!=='ACTIVE'||($j['expiresAt']&&strtotime($j['expiresAt'])<time()))throw new Error(409,'Job closed');$cv=$this->owned('cv_files',$r->required('cvFileId'));return $this->db->transaction(function()use($r,$u,$j,$cv){if($this->db->one('SELECT id FROM applications WHERE job_id=? AND candidate_id=?',[$j['id'],$u['id']]))throw new Error(409,'Already applied');$a=$this->db->write('applications',['jobId'=>$j['id'],'candidateId'=>$u['id'],'cvFileId'=>$cv['id'],'coverLetter'=>$r->body['coverLetter']??null]);$this->queue('SCREEN',['applicationId'=>$a['id']]);$this->history($a['id'],'APPLIED',$u['id']);return $a;});});
        $this->route('GET','applications/me',function(){$u=$this->auth->role(['CANDIDATE']);return array_map([$this,'application'],$this->db->records('applications','candidate_id=?',[$u['id']],'applied_at DESC'));});
        $this->route('GET','applications/job/{id}/export',function(Request $r,array $p){$j=$this->find('jobs',['id'=>$p['id']]);$this->auth->company($j['companyId']);header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="applications.csv"');$out=fopen('php://output','w');fwrite($out,"\xEF\xBB\xBF");fputcsv($out,['ID','Candidate','Status','Score']);foreach($this->db->records('applications','job_id=?',[$j['id']]) as $a){$a=$this->application($a);$name=$a['candidate']['profile']['fullName']??'';if(preg_match('/^[=+@-]/',$name))$name="'".$name;fputcsv($out,[$a['id'],$name,$a['status'],$a['aiResult']['overallScore']??'']);}fclose($out);return null;});
        $this->route('GET','applications/job/{id}',function(Request $r,array $p){$j=$this->find('jobs',['id'=>$p['id']]);$this->auth->company($j['companyId']);return array_map([$this,'application'],$this->db->records('applications','job_id=?',[$j['id']]));});
        $this->route('GET','applications/{id}',function(Request $r,array $p){return $this->application($this->access($p['id']));});
        $this->route('DELETE','applications/{id}',function(Request $r,array $p){$a=$this->owned('applications',$p['id'],'candidateId');if(in_array($a['status'],['HIRED','REJECTED','WITHDRAWN'],true))throw new Error(409,'Cannot withdraw');return $this->transition($a,'WITHDRAWN',$this->auth->current()['id']);});
        $this->route('POST','applications/{id}/reapply',function(Request $r,array $p){$a=$this->owned('applications',$p['id'],'candidateId');if($a['status']!=='WITHDRAWN')throw new Error(409,'Application was not withdrawn');return $this->db->transaction(function()use($a){$v=$this->transition($a,'APPLIED',$a['candidateId']);$this->queue('SCREEN',['applicationId'=>$a['id']]);return $v;});});
        $this->route('PATCH','applications/{id}/status',function(Request $r,array $p){$a=$this->access($p['id'],true);$status=$r->choice('status',['HR_REVIEW','INTERVIEW','OFFER','HIRED','REJECTED']);return $this->transition($a,$status,$this->auth->current()['id'],$r->body['note']??null);});
        $this->route('POST','applications/{id}/rescreen',function(Request $r,array $p){$a=$this->access($p['id'],true);return ['taskId'=>$this->queue('SCREEN',['applicationId'=>$a['id'],'rescreen'=>true])];});
        $this->route('POST','applications/{id}/schedule-interview',function(Request $r,array $p){$a=$this->access($p['id'],true);$at=$r->required('interviewAt');try{$d=new \DateTimeImmutable($at);}catch(\Exception $e){throw new Error(400,'Invalid interview date');}return $this->transition($a,'INTERVIEW',$this->auth->current()['id'],'Interview: '.$d->format(DATE_ATOM).' '.($r->body['note']??''));});
        $this->route('POST','applications/{id}/offer',function(Request $r,array $p){$a=$this->access($p['id'],true);$u=$this->auth->current();return $this->db->transaction(function()use($r,$a,$u){$old=$this->db->one('SELECT id FROM offers WHERE application_id=?',[$a['id']]);$data=$this->only($r->body,['salaryAmount','salaryCurrency','startDate','responseDeadline','note','offerLetterUrl']);$data['status']='PENDING';$data['createdBy']=$u['id'];$offer=$old?$this->db->write('offers',$data,$old):$this->db->write('offers',array_merge($data,['applicationId'=>$a['id']]));$this->transition($a,'OFFER',$u['id']);return $offer;});});
        $this->route('POST','applications/{id}/offer/respond',function(Request $r,array $p){$a=$this->owned('applications',$p['id'],'candidateId');$decision=$r->choice('action',['accept','decline']);return $this->db->transaction(function()use($r,$a,$decision){$raw=$this->db->one('SELECT * FROM offers WHERE application_id=? FOR UPDATE',[$a['id']]);if(!$raw)throw new Error(404,'Offer missing');$o=$this->db->map('offers',$raw);if($o['status']!=='PENDING'||($o['responseDeadline']&&strtotime($o['responseDeadline'])<time()))throw new Error(409,'Offer no longer pending');$o=$this->db->write('offers',['status'=>$decision==='accept'?'ACCEPTED':'DECLINED','respondedAt'=>\now(),'declineReason'=>$r->body['reason']??null],['id'=>$o['id']]);$this->transition($a,$decision==='accept'?'HIRED':'REJECTED',$a['candidateId']);return $o;});});
        $this->route('GET','job-alerts',function(){return $this->db->records('job_alerts','user_id=?',[$this->auth->current()['id']]);});
        $this->route('POST','job-alerts',function(Request $r){$u=$this->auth->current();$data=$this->only($r->body,['keyword','filters','isActive']);$data['frequency']=$r->choice('frequency',['DAILY','WEEKLY','INSTANT'],'DAILY');$data['userId']=$u['id'];return $this->db->write('job_alerts',$data);});
        $this->route('PATCH','job-alerts/{id}',function(Request $r,array $p){$this->owned('job_alerts',$p['id']);$data=$this->only($r->body,['keyword','filters','isActive','frequency']);if(isset($data['frequency']))$r->choice('frequency',['DAILY','WEEKLY','INSTANT']);return $this->db->write('job_alerts',$data,['id'=>$p['id']]);});
        $this->route('DELETE','job-alerts/{id}',function(Request $r,array $p){$this->owned('job_alerts',$p['id']);$this->db->delete('job_alerts',['id'=>$p['id']]);return ['ok'=>true];});
    }
    private function job(array $j): array {$j['company']=$this->find('companies',['id'=>$j['companyId']]);return $j;}
    private function jobs(string $where,array $args): array {return array_map([$this,'job'],$this->db->records('jobs',$where,$args,'published_at DESC'));}
    private function search(Request $r): array {
        $where=["status='ACTIVE'"]; $args=[];
        $q=$r->query['keyword']??($r->query['q']??'');if($q!==''){$where[]='(title LIKE ? OR description LIKE ?)';$args[]='%'.$q.'%';$args[]='%'.$q.'%';}
        foreach(['location'=>'location','category'=>'category','level'=>'level','jobType'=>'job_type','companyId'=>'company_id'] as $key=>$column)if(!empty($r->query[$key])){$where[]='`'.$column.'`'.($key==='location'?' LIKE ?':'=?');$args[]=$key==='location'?'%'.$r->query[$key].'%':$r->query[$key];}
        if(isset($r->query['salaryMin'])){$where[]='(max_salary>=? OR max_salary IS NULL)';$args[]=(int)$r->query['salaryMin'];}
        if(isset($r->query['salaryMax'])){$where[]='(min_salary<=? OR min_salary IS NULL)';$args[]=(int)$r->query['salaryMax'];}
        if(!empty($r->query['skills'])){$skills=is_array($r->query['skills'])?$r->query['skills']:explode(',',$r->query['skills']);$checks=[];foreach(array_slice($skills,0,20) as $s){$checks[]='JSON_CONTAINS(required_skills,?)';$args[]=json_encode(trim($s));}$where[]='('.implode(' OR ',$checks).')';}
        if(isset($r->query['isRemote'])){$where[]='is_remote=?';$args[]=$r->query['isRemote']==='true'?1:0;}
        $u=$this->auth->current(false);if(($r->query['mine']??'')==='true'){if(!$u)throw new Error(401,'Sign in required');$where[0]='1';$where[]='company_id IN (SELECT company_id FROM company_members WHERE user_id=?)';$args[]=$u['id'];}
        $sql=implode(' AND ',$where);$total=(int)$this->db->one('SELECT COUNT(*) n FROM jobs WHERE '.$sql,$args)['n'];$limit=$this->limit($r);$page=$this->page($r);
        $sort=['salary'=>'max_salary','relevance'=>'views_count'][$r->query['sort']??'']??'published_at';
        $rows=$this->db->all('SELECT * FROM jobs WHERE '.$sql.' ORDER BY '.$sort.' DESC,id DESC LIMIT '.$limit.' OFFSET '.(($page-1)*$limit),$args);
        return ['items'=>array_map(function($j){return $this->job($this->db->map('jobs',$j));},$rows),'pagination'=>['page'=>$page,'pageSize'=>$limit,'total'=>$total,'totalPages'=>max(1,(int)ceil($total/$limit))],'total'=>$total,'page'=>$page,'limit'=>$limit];
    }
    private function access(string $id,bool $recruiter=false): array {$a=$this->find('applications',['id'=>$id]);$u=$this->auth->current();if(!$recruiter&&$u['id']===$a['candidateId'])return $a;$j=$this->find('jobs',['id'=>$a['jobId']]);$this->auth->company($j['companyId']);return $a;}
    private function application(array $a): array {$a['job']=$this->job($this->find('jobs',['id'=>$a['jobId']]));$a['cvFile']=$this->find('cv_files',['id'=>$a['cvFileId']]);$a['candidate']=$this->safeUser($this->find('users',['id'=>$a['candidateId']]));$a['aiResult']=$this->db->records('ai_screening_results','application_id=?',[$a['id']])[0]??null;$a['offer']=$this->db->records('offers','application_id=?',[$a['id']])[0]??null;$a['statusHistory']=$this->db->records('application_status_history','application_id=?',[$a['id']],'changed_at ASC');$a['interviewAt']=null;$a['interviewNote']=null;foreach($a['statusHistory'] as $entry){if($entry['toStatus']==='INTERVIEW'&&preg_match('/^Interview: (\S+)\s*(.*)$/s',$entry['note']??'',$match)){$a['interviewAt']=$match[1];$a['interviewNote']=$match[2];}}return $a;}
    private function history(string $id,string $status,string $user,?string $note=null,?string $from=null): void {$this->db->write('application_status_history',['applicationId'=>$id,'fromStatus'=>$from,'toStatus'=>$status,'changedBy'=>$user,'note'=>$note]);}
    private function transition(array $a,string $status,string $user,?string $note=null): array {
        $fn=function()use($a,$status,$user,$note){
            $current=$this->db->one('SELECT status FROM applications WHERE id=? FOR UPDATE',[$a['id']]);
            if(!$current||$current['status']!==$a['status'])throw new Error(409,'Application changed; refresh and try again');
            if($current['status']===$status)return $a;
            if(in_array($current['status'],['HIRED','REJECTED'],true)||($current['status']==='WITHDRAWN'&&$status!=='APPLIED'))throw new Error(409,'Application is closed');
            $new=$this->db->write('applications',['status'=>$status],['id'=>$a['id']]);$this->history($a['id'],$status,$user,$note,$current['status']);$this->notify($a['candidateId'],'APPLICATION_STATUS','Application updated',$status,['applicationId'=>$a['id']]);return $new;
        };
        return $this->db->pdo->inTransaction()?$fn():$this->db->transaction($fn);
    }
    private function analytics(string $id): array {return ['jobs'=>$this->db->all('SELECT status,COUNT(*) total FROM jobs WHERE company_id=? GROUP BY status',[$id]),'applications'=>$this->db->all('SELECT a.status,COUNT(*) total FROM applications a JOIN jobs j ON j.id=a.job_id WHERE j.company_id=? GROUP BY a.status',[$id]),'scores'=>$this->db->one('SELECT AVG(s.overall_score) averageScore FROM ai_screening_results s JOIN applications a ON a.id=s.application_id JOIN jobs j ON j.id=a.job_id WHERE j.company_id=?',[$id])];}
}
