<?php
declare(strict_types=1);
namespace Platform\Controllers;
use Platform\Http\Request;
use Platform\Http\Error;
use Platform\Services\Visibility;
class Social extends Controller {
    protected function routes(): void {
        $this->route('GET','feed',function(Request $r){
            $u=$this->auth->current(false);$where=['deleted_at IS NULL'];$args=[];
            if(!empty($r->query['authorId'])){$where[]='author_id=?';$args[]=$r->query['authorId'];}
            if(!empty($r->query['cursor'])){$cursor=$this->db->record('posts',['id'=>$r->query['cursor']]);if(!$cursor)throw new Error(400,'Invalid cursor');$where[]='(created_at<? OR (created_at=? AND id<?))';$t=(new \DateTimeImmutable($cursor['createdAt']))->format('Y-m-d H:i:s.v');array_push($args,$t,$t,$cursor['id']);}
            $limit=min(50,$this->limit($r));$rows=$this->db->records('posts',implode(' AND ',$where),$args,'created_at DESC,id DESC');$out=[];$v=new Visibility($this->db);
            foreach($rows as $p){if($v->post($p,$u))$out[]=$this->post($p,$u);if(count($out)===$limit)break;}return $out;
        });
        $this->route('GET','social/posts/{id}',function(Request $r,array $p){$u=$this->auth->current(false);return $this->post((new Visibility($this->db))->requirePost($p['id'],$u),$u);});
        $this->route('POST','social/posts',function(Request $r){$u=$this->auth->current();if(!is_string($r->body['content']??null))throw new Error(400,'Content must be a string');if(mb_strlen($r->required('content'))>5000)throw new Error(400,'Post too long');$media=$r->body['mediaUrls']??[];if(!is_array($media)||count($media)>10)throw new Error(400,'Up to 10 attachments');foreach($media as $url){if(!is_string($url)||!preg_match('#^/api/v1/files/media/#',$url))throw new Error(400,'Upload attachments first');if(!$this->db->one('SELECT storage_key FROM stored_files WHERE storage_key=? AND owner_id=?',[substr($url,14),$u['id']]))throw new Error(403,'Attachment owner required');}if(!empty($r->body['companyId']))$this->auth->company($r->body['companyId']);return $this->post($this->db->write('posts',['authorId'=>$u['id'],'content'=>$r->required('content'),'companyId'=>$r->body['companyId']??null,'mediaUrls'=>$r->body['mediaUrls']??[],'visibility'=>$r->choice('visibility',['PUBLIC','CONNECTIONS','PRIVATE'],'PUBLIC')]),$u);});
        $this->route('DELETE','social/posts/{id}',function(Request $r,array $p){$this->owned('posts',$p['id'],'authorId');return $this->db->write('posts',['deletedAt'=>\now()],['id'=>$p['id']]);});
        $this->route('POST','social/posts/{id}/comments',function(Request $r,array $p){$u=$this->auth->current();if(!is_string($r->body['content']??null)||mb_strlen($r->required('content'))>1200)throw new Error(400,'Comment must contain at most 1200 characters');$post=(new Visibility($this->db))->requirePost($p['id'],$u);$parent=$r->body['parentId']??null;if($parent!==null&&(!is_string($parent)||!preg_match('/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i',$parent)))throw new Error(400,'Invalid parent comment');if($parent){$c=$this->find('comments',['id'=>$parent]);if($c['postId']!==$post['id']||$c['deletedAt'])throw new Error(400,'Invalid parent comment');}return $this->db->transaction(function()use($r,$u,$post,$parent){$c=$this->db->write('comments',['authorId'=>$u['id'],'postId'=>$post['id'],'parentId'=>$parent,'content'=>$r->required('content')]);$this->db->run('UPDATE posts SET comment_count=comment_count+1 WHERE id=?',[$post['id']]);if($u['id']!==$post['authorId'])$this->notify($post['authorId'],'COMMENT','New comment',$c['content'],['postId'=>$post['id']]);return $this->comment($c,$u);});});
        foreach(['posts'=>'POST','comments'=>'COMMENT'] as $path=>$type)$this->route('POST','social/'.$path.'/{id}/reactions',function(Request $r,array $p)use($type){$u=$this->auth->current();$target=$this->find($type==='POST'?'posts':'comments',['id'=>$p['id']]);(new Visibility($this->db))->requirePost($type==='POST'?$target['id']:$target['postId'],$u);if($type==='COMMENT'&&$target['deletedAt'])throw new Error(404,'Comment missing');$reaction=$r->choice('reactionType',['LIKE','LOVE','HAHA','WOW','SAD','ANGRY','CELEBRATE','SUPPORT','INSIGHTFUL'],'LIKE');return $this->db->transaction(function()use($u,$p,$type,$reaction){$key=['userId'=>$u['id'],'targetType'=>$type,'targetId'=>$p['id']];$old=$this->db->record('reactions',$key);if($old&&$old['reactionType']===$reaction){$this->db->delete('reactions',$key);$value=null;}else{$old?$this->db->write('reactions',['reactionType'=>$reaction],$key):$this->db->write('reactions',array_merge($key,['reactionType'=>$reaction]));$value=$reaction;}$total=(int)$this->db->one('SELECT COUNT(*) n FROM reactions WHERE target_type=? AND target_id=?',[$type,$p['id']])['n'];if($type==='POST')$this->db->write('posts',['likeCount'=>$total],['id'=>$p['id']]);return ['userReaction'=>$value,'totalReactions'=>$total,'likeCount'=>$total];});});
        $this->route('GET','social/connections/suggestions',function(){return $this->suggestions();});
        $this->route('GET','social/connections',function(){$u=$this->auth->current();$rows=$this->db->records('connections','requester_id=? OR addressee_id=?',[$u['id'],$u['id']]);foreach($rows as &$c){$c['requester']=$this->safeUser($this->find('users',['id'=>$c['requesterId']]));$c['addressee']=$this->safeUser($this->find('users',['id'=>$c['addresseeId']]));}return $rows;});
        $this->route('POST','social/connections',function(Request $r){$u=$this->auth->current();$id=$r->required('addresseeId');$this->find('users',['id'=>$id]);if($id===$u['id'])throw new Error(400,'Cannot connect to self');$existing=$this->db->one('SELECT id FROM connections WHERE (requester_id=? AND addressee_id=?) OR (requester_id=? AND addressee_id=?)',[$u['id'],$id,$id,$u['id']]);if($existing)throw new Error(409,'Connection already exists');return $this->db->transaction(function()use($u,$id){$c=$this->db->write('connections',['requesterId'=>$u['id'],'addresseeId'=>$id,'status'=>'PENDING']);$this->notify($id,'CONNECTION_REQUEST','Lời mời kết nối','Bạn có lời mời kết nối mới',['connectionId'=>$c['id'],'url'=>'/network']);return $c;});});
        $this->route('PATCH','social/connections/{id}/status',function(Request $r,array $p){$u=$this->auth->current();$c=$this->find('connections',['id'=>$p['id']]);$status=$r->choice('status',['ACCEPTED','BLOCKED']);if(!in_array($u['id'],[$c['requesterId'],$c['addresseeId']],true)||($status==='ACCEPTED'&&($u['id']!==$c['addresseeId']||$c['status']!=='PENDING')))throw new Error(403,'Cannot change connection');$updated=$this->db->write('connections',['status'=>$status],['id'=>$c['id']]);if($status==='ACCEPTED')$this->notify($c['requesterId'],'CONNECTION_ACCEPTED','Đã chấp nhận kết nối','Lời mời kết nối của bạn đã được chấp nhận',['connectionId'=>$c['id'],'url'=>'/network']);return $updated;});
        $this->route('DELETE','social/connections/{id}',function(Request $r,array $p){$u=$this->auth->current();$c=$this->find('connections',['id'=>$p['id']]);if(!in_array($u['id'],[$c['requesterId'],$c['addresseeId']],true))throw new Error(403,'Access denied');$this->db->delete('connections',['id'=>$c['id']]);return ['ok'=>true];});
        $this->route('GET','social/users/{id}/follow',function(Request $r,array $p){$u=$this->auth->current();return ['following'=>(bool)$this->db->record('user_follows',['followerId'=>$u['id'],'followedId'=>$p['id']]),'followerCount'=>(int)$this->db->one('SELECT COUNT(*) n FROM user_follows WHERE followed_id=?',[$p['id']])['n']];});
        foreach(['POST','DELETE'] as $method)$this->route($method,'social/users/{id}/follow',function(Request $r,array $p)use($method){$u=$this->auth->current();$this->find('users',['id'=>$p['id']]);if($u['id']===$p['id']||(new Visibility($this->db))->blocked($u['id'],$p['id']))throw new Error(403,'Cannot follow');$key=['followerId'=>$u['id'],'followedId'=>$p['id']];if($method==='DELETE'){$this->db->delete('user_follows',$key);return $this->followState($u['id'],$p['id']);}$this->db->record('user_follows',$key)??$this->db->write('user_follows',$key);return $this->followState($u['id'],$p['id']);});
        $this->route('GET','recommendations/people',function(){return $this->suggestions();});
    }
    private function followState(string $viewer,string $subject): array {return ['following'=>(bool)$this->db->record('user_follows',['followerId'=>$viewer,'followedId'=>$subject]),'followerCount'=>(int)$this->db->one('SELECT COUNT(*) n FROM user_follows WHERE followed_id=?',[$subject])['n']];}
    private function suggestions(): array {$u=$this->auth->current();$rows=$this->db->records('users',"deleted_at IS NULL AND id<>? AND id NOT IN (SELECT addressee_id FROM connections WHERE requester_id=? UNION SELECT requester_id FROM connections WHERE addressee_id=?)",[$u['id'],$u['id'],$u['id']]);return array_map([$this,'safeUser'],array_slice($rows,0,20));}
    private function comment(array $comment,?array $viewer): array {
        $comment['author']=['id'=>$comment['authorId'],'profile'=>$this->db->record('user_profiles',['userId'=>$comment['authorId']])];
        $comment['userReaction']=$viewer?($this->db->record('reactions',['userId'=>$viewer['id'],'targetType'=>'COMMENT','targetId'=>$comment['id']])['reactionType']??null):null;
        return $comment;
    }
    private function post(array $p,?array $u): array {
        $a=$this->find('users',['id'=>$p['authorId']]);$p['author']=['id'=>$a['id'],'profile'=>$this->db->record('user_profiles',['userId'=>$a['id']])];$p['company']=$p['companyId']?$this->db->record('companies',['id'=>$p['companyId']]):null;
        $p['comments']=$this->db->records('comments','post_id=? AND deleted_at IS NULL',[$p['id']],'created_at ASC');
        foreach($p['comments'] as &$c)$c=$this->comment($c,$u);
        $p['userReaction']=$u?($this->db->record('reactions',['userId'=>$u['id'],'targetType'=>'POST','targetId'=>$p['id']])['reactionType']??null):null;
        $fresh=max(0,72-(time()-strtotime($p['createdAt']))/3600)/72;$p['feedScore']=round($fresh*50+$p['likeCount']*1.4+$p['commentCount']*2,2);return $p;
    }
}
