<?php use Platform\Services\CvParser;
if(!$score): ?><section class="panel empty section"><h2>AI đang phân tích hồ sơ</h2><p class="muted">Kết quả sẽ được cập nhật khi quá trình đánh giá hoàn tất.</p></section><?php else:
$raw=$data['cvFile']['extractedText']??'';$required=$data['job']['requiredSkills']??[];$parsed=CvParser::parse($raw,$required);$analysis=$parsed['hasText']?CvParser::compare($raw,$required):['matched'=>$score['matchedSkills'],'missing'=>$score['missingSkills'],'extra'=>[],'matchPct'=>$required?(int)round(count($score['matchedSkills'])/count($required)*100):0];
$skillName=function($s){return is_array($s)?($s['name']??$s['skill']??''):$s;};
$criteria=['skillScore'=>['Kỹ năng chuyên môn',40,75],'experienceScore'=>['Kinh nghiệm làm việc',30,70],'educationScore'=>['Nền tảng học vấn',20,65],'otherScore'=>['Tiêu chí khác',10,60]];
?>
<div class="grid two section"><section class="panel"><h2><?= ui_icon('sparkles',20) ?> Tổng quan AI Score</h2><div class="analytics-donut" style="--chart-progress:<?= max(0,min(100,(float)$score['overallScore'])) ?>%"><div><strong><?= e($score['overallScore']) ?></strong><span>Điểm phù hợp /100 · <?= e($score['grade']) ?></span></div></div><p><?= e($score['explanation']) ?></p><small class="muted"><?= e($score['modelVersion']) ?> · <?= (int)$score['processingTimeMs'] ?> ms</small></section>
<section class="panel"><h2>Phân tích tiêu chí</h2><div class="ai-criteria section"><?php foreach($criteria as $key=>[$label,$weight,$benchmark]): ?><div><span><?= e($label) ?></span><strong><?= e($score[$key]) ?> <small>/100</small></strong><p class="muted">Trọng số <?= $weight ?>% · Đóng góp <?= number_format((float)$score[$key]*$weight/100,1) ?> điểm</p><meter max="100" min="0" value="<?= e($score[$key]) ?>" aria-label="<?= e($label) ?>"></meter><small class="muted">Mốc tham chiếu: <?= $benchmark ?></small></div><?php endforeach; ?></div></section></div>
<div class="grid two section"><section class="panel"><h2>Hồ sơ ứng viên</h2><div class="person-identity section"><?= ui_avatar($data['candidate']['profile']??[],56) ?><div><strong><?= e($data['candidate']['profile']['fullName']??'') ?></strong><p><?= e($data['candidate']['profile']['headline']??'') ?></p><p class="muted"><?= e($data['candidate']['email']) ?></p></div></div><p><?= e($data['candidate']['profile']['about']??'') ?></p><a class="button ghost" href="<?= e(safe_url($data['cvFile']['fileUrl'])) ?>" target="_blank" rel="noopener">Xem CV</a></section>
<section class="panel"><h2>Mức độ phù hợp JD</h2><p class="positive"><?= $analysis['matchPct'] ?>% kỹ năng yêu cầu</p><?php foreach(['matched'=>'Kỹ năng phù hợp','missing'=>'Kỹ năng còn thiếu','extra'=>'Kỹ năng bổ sung'] as $key=>$label): ?><h3 class="section"><?= e($label) ?></h3><div class="chips"><?php foreach($analysis[$key] as $skill): ?><span class="<?= $key==='matched'?'skill-match':'' ?>"><?= e($skillName($skill)) ?></span><?php endforeach; if(!$analysis[$key]): ?><span class="muted">Chưa có thông tin</span><?php endif; ?></div><?php endforeach; ?></section></div>
<div class="grid two section"><section class="panel"><h2>Thông tin đọc được từ CV</h2><p class="muted"><?= e($data['cvFile']['fileName']) ?></p><?php if($parsed['hasText']): ?>
<?php foreach(['email'=>'Email','phone'=>'Điện thoại'] as $key=>$label):if($parsed['contact'][$key]): ?><p><?= e($label) ?>: <?= e($parsed['contact'][$key]) ?></p><?php endif; endforeach; ?><p>Kinh nghiệm: <?= e($parsed['totalYears']) ?> năm</p>
<?php foreach(['skills'=>'Kỹ năng','education'=>'Học vấn','certifications'=>'Chứng chỉ','languages'=>'Ngôn ngữ'] as $key=>$label):if($parsed[$key]): ?><h3><?= e($label) ?></h3><div class="chips"><?php foreach($parsed[$key] as $text): ?><span><?= e($text) ?></span><?php endforeach; ?></div><?php endif; endforeach; ?>
<?php foreach($parsed['sections'] as $section): ?><details class="section"><summary><?= e($section['title']) ?></summary><p class="prose"><?= nl2br(e($section['content'])) ?></p></details><?php endforeach; ?>
<details class="section"><summary>Xem toàn bộ văn bản CV</summary><pre class="cv-text-preview"><?= e($raw) ?></pre></details>
<?php else: ?><p class="muted">CV chưa có văn bản trích xuất.</p><?php endif; ?></section>
<section class="panel"><h2>So khớp CV với mô tả công việc</h2><p class="muted"><?= $parsed['hasText']?'Phân tích dựa trên văn bản đã đọc từ CV.':'Phân tích dựa trên kết quả AI.' ?></p><p class="prose"><?= nl2br(e(strip_tags($data['job']['description']))) ?></p><h3>Kỹ năng yêu cầu</h3><div class="chips"><?php foreach($required as $skill): ?><span><?= e($skill) ?></span><?php endforeach; ?></div></section></div>
<div class="grid two section"><section class="panel"><h2>Bảng kỹ năng</h2><div class="table-scroll"><table><thead><tr><th>Kỹ năng</th><th>Số năm</th><th>Cấp độ</th></tr></thead><tbody><?php foreach($data['candidate']['userSkills']??[] as $skill): ?><tr><td><?= e($skill['skill']['name']??'') ?></td><td><?= e($skill['yearsExp']??'—') ?></td><td><?= e(['BEGINNER'=>'Cơ bản','INTERMEDIATE'=>'Trung cấp','ADVANCED'=>'Nâng cao','EXPERT'=>'Chuyên gia'][$skill['level']]??$skill['level']) ?></td></tr><?php endforeach; ?></tbody></table></div><?php if(empty($data['candidate']['userSkills'])): ?><p class="muted">Chưa có kỹ năng trong hồ sơ.</p><?php endif; ?></section>
<section class="panel"><h2>Phân tích kỹ năng</h2><p><?= count($analysis['matched']) ?>/<?= count($required) ?> kỹ năng yêu cầu phù hợp.</p><progress max="100" value="<?= $analysis['matchPct'] ?>" aria-label="Tỷ lệ kỹ năng phù hợp"></progress><p><?= count($analysis['missing']) ?> kỹ năng cần làm rõ khi phỏng vấn.</p></section></div>
<div class="grid two section"><section class="panel"><h2><?= ui_icon('briefcase',18) ?> Kinh nghiệm</h2><?php foreach($data['candidate']['workExperiences']??[] as $experience): ?><article class="raised section"><h3><?= e($experience['position']) ?></h3><p><?= e($experience['company']) ?></p><p class="muted"><?= e(date('m/Y',strtotime($experience['startDate']))) ?> – <?= $experience['endDate']?e(date('m/Y',strtotime($experience['endDate']))):'Hiện tại' ?></p><p class="prose"><?= nl2br(e($experience['description']??'')) ?></p></article><?php endforeach; if(empty($data['candidate']['workExperiences'])): ?><p class="muted">Chưa có kinh nghiệm trong hồ sơ.</p><?php endif; ?></section>
<section class="panel"><h2>Học vấn</h2><?php foreach($data['candidate']['educations']??[] as $education): ?><article class="raised section"><h3><?= e($education['school']) ?></h3><p><?= e($education['degree']) ?> · <?= e($education['major']??'') ?></p><p class="muted"><?= e($education['startYear']??'—') ?> – <?= e($education['endYear']??'Hiện tại') ?><?= isset($education['gpa'])?' · GPA '.e($education['gpa']):'' ?></p></article><?php endforeach; if(empty($data['candidate']['educations'])): ?><p class="muted">Chưa có học vấn trong hồ sơ.</p><?php endif; ?></section></div>
<section class="panel section"><h2>Đánh giá chi tiết</h2><div class="grid two"><div><h3>Điểm mạnh</h3><ul><?php foreach($score['strengths'] as $text): ?><li><?= e($text) ?></li><?php endforeach; ?></ul></div><div><h3>Cần cải thiện</h3><ul><?php foreach($score['concerns'] as $text): ?><li><?= e($text) ?></li><?php endforeach; ?></ul></div></div></section>
<section class="panel section"><h2>Lịch sử trạng thái</h2><?php require APP_ROOT.'/views/partials/application-history.php'; ?></section>
<?php endif; ?>
