<?php require_once APP_ROOT.'/views/partials/comment-thread.php'; ?>
<article class="panel section" data-feed-post data-post-id="<?= e($post['id']) ?>" data-author="<?= e($post['authorId']) ?>" data-media="<?= count($post['mediaUrls']??[]) ?>" data-engagement="<?= (int)$post['likeCount']+(int)$post['commentCount']*2 ?>" data-score="<?= e($post['feedScore']) ?>" data-created="<?= e($post['createdAt']) ?>">
<div class="feed-author"><a href="/u/<?= e($post['authorId']) ?>"><?= ui_avatar($post['author']['profile']??[]) ?></a><div><a href="/u/<?= e($post['authorId']) ?>"><strong><?= e($post['author']['profile']['fullName']??'Thành viên') ?></strong></a><p class="muted"><?= e((new DateTimeImmutable($post['createdAt']))->setTimezone(new DateTimeZone('Asia/Ho_Chi_Minh'))->format('d/m/Y H:i')) ?></p></div></div>
<p class="prose"><?= nl2br(e($post['content'])) ?></p>
<?php foreach($post['mediaUrls']??[] as $url): if(is_string($url)&&preg_match('#^(https?://|/)#',$url)): ?><a href="<?= e(safe_url($url)) ?>" target="_blank" rel="noopener noreferrer"><?php if(preg_match('/\.(png|jpe?g|webp|gif)(?:\?|$)/i',$url)): ?><img class="post-image" src="<?= e(safe_url($url)) ?>" alt="Ảnh đính kèm bài viết" loading="lazy"><?php else: ?><?= ui_icon('file',18) ?> <?= e(basename($url)) ?><?php endif; ?></a><?php endif; endforeach; ?>
<p class="muted"><span data-like-count><?= (int)$post['likeCount'] ?></span> tương tác · <span data-comment-count><?= (int)$post['commentCount'] ?></span> bình luận</p>
<div class="reaction-toolbar"><?php ui_reaction_picker('/social/posts/'.$post['id'].'/reactions',$post['userReaction'],$user!==null); ?><button type="button" class="ghost" data-show-comments="comments-<?= e($post['id']) ?>" aria-expanded="false"><?= ui_icon('message',16) ?> Bình luận</button><button type="button" class="ghost" data-copy-post="<?= e($post['id']) ?>"><?= ui_icon('share',16) ?> Chia sẻ</button><?php if($user&&$post['authorId']===$user['id']): ?><button class="ghost" data-action="/social/posts/<?= e($post['id']) ?>" data-method="DELETE" data-reload>Xóa bài</button><?php endif; ?></div>
<?php ui_comment_thread($post,$user!==null,!empty($profileActivity)); ?>
<?php if($user): ?><details><summary>Báo cáo bài viết</summary><form data-api="/moderation/reports"><input type="hidden" name="contentType" value="POST"><input type="hidden" name="targetId" value="<?= e($post['id']) ?>"><input name="reason" required placeholder="Lý do"><button type="submit">Gửi báo cáo</button></form></details><?php endif; ?>
</article>
