<?php $internal=isset($job['companyId']);$companyName=$internal?$job['company']['name']:($job['company']??'');$jobSkills=$internal?($job['requiredSkills']??[]):($job['skills']??[]);$saved=in_array($job['id'],$savedIds??[],true); ?>
<?php if($internal):require APP_ROOT.'/views/partials/internal-job-card.php';else: ?>
<article class="panel job-card"><div class="job-top"><?php if($internal): ?><div class="row" style="align-items:start"><span class="job-logo"><?= e(mb_substr($companyName,0,1)) ?></span><div><h3><a href="/jobs/<?= e($job['id']) ?>"><?= e($job['title']) ?></a></h3><p class="job-company"><?= e($companyName) ?></p></div></div><?php else: ?><div><span class="job-source source-<?= e($job['source']) ?>"><?= e(['itviec'=>'ITviec','careerviet'=>'CareerViet','topcv'=>'TopCV','vietnamworks'=>'VietnamWorks'][$job['source']]??$job['source']) ?></span><h3><button class="job-title-button" data-job-summary="<?= e($job['id']) ?>"><?= e($job['title']) ?></button></h3></div><?php endif; ?>
<?php if($user): ?><button class="icon-button <?= $saved?'positive':'' ?>" data-job-save="<?= e($job['id']) ?>" data-external="<?= $internal?'false':'true' ?>" aria-label="<?= $saved?'Bỏ lưu việc làm':'Lưu việc làm' ?>" aria-pressed="<?= $saved?'true':'false' ?>"><?= ui_icon('bookmark',18) ?></button><?php endif; ?></div>
<?php if(!$internal): ?><p class="job-meta"><?= ui_icon('building',14) ?><?= e($companyName) ?></p><?php endif; ?><p class="job-meta"><?= ui_icon('pin',14) ?><?= e($job['location']??'Linh hoạt') ?></p><p class="job-meta"><?= ui_icon('wallet',14) ?><?= e($job['salary']??(($job['minSalary']??null)?number_format((float)$job['minSalary']).' – '.number_format((float)($job['maxSalary']??$job['minSalary'])).' '.($job['salaryCurrency']??'VND'):'Thương lượng')) ?></p>
<?php if($internal): ?><div class="chips"><span><?= e($job['jobType']) ?></span><span><?= e($job['level']) ?></span><?php if($job['isRemote']): ?><span class="skill-match">Remote</span><?php endif; ?></div><?php else: ?><p class="job-meta"><?= ui_icon('clock',14) ?>Cập nhật <?= e((new DateTimeImmutable($job['crawledAt']))->format('d/m/Y')) ?></p><?php endif; ?>
<?php if($jobSkills): ?><div class="chips"><?php foreach(array_slice($jobSkills,0,7) as $skill): ?><span class="<?= in_array(strtolower($skill),$userSkillNames??[],true)?'skill-match':'' ?>"><?= e($skill) ?></span><?php endforeach; ?></div><?php endif; ?>
<div class="job-actions"><?php if($internal): ?><a class="button" href="/jobs/<?= e($job['id']) ?>">Xem chi tiết <?= ui_icon('arrow',16) ?></a><?php else: ?><button data-job-screen="<?= e($job['id']) ?>" data-title="<?= e($job['title']) ?>"><?= ui_icon('sparkles',16) ?>Chấm điểm CV</button><a class="button secondary" href="<?= e(safe_url($job['url'])) ?>" target="_blank" rel="noopener noreferrer">Xem tin</a><?php endif; ?></div></article>

<?php endif; ?>
